GatherItems = {
	[1] = {
		[2] = {
			["silver vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 75.43000000000001,
					["count"] = 3,
					["icon"] = 3,
					["y"] = 48.8,
				},
			},
			["iron deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 71.14,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 60.55,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 70.72,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 53.54,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 58.27,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 31.15,
				},
			},
		},
		[10] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 47.88,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 37.53,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 61.92,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 22.27,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 60.74,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 22.34,
				},
			},
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 42.8,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 40.28,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 57.36,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 25.64,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 60.26,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 22.89,
				},
			},
		},
		[27] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 77.09999999999999,
					["count"] = 3,
					["icon"] = 7,
					["y"] = 54.61,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 60.47,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 67.95,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 64.47,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 80.34,
				},
			},
			["ooze covered truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 45.29,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 87.74,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 47.98,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 80.99,
				},
			},
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 50.55,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 75.45999999999999,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 76.88,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 49.51,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 59.52,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 65.54000000000001,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 56.7,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 11.65,
				},
			},
		},
		[21] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 61.65,
					["count"] = 3,
					["icon"] = 7,
					["y"] = 63.52,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 33.22,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 42.77,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 33.26,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 41.33,
				},
			},
			["mithril deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 54.25,
					["count"] = 2,
					["icon"] = 6,
					["y"] = 24.49,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 33.35,
					["count"] = 5,
					["icon"] = 6,
					["y"] = 41.61,
				},
			},
			["iron deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 56.78,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 36.68,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 56.26,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 37.07,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 56.13,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 37.87,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 61.05,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 41.04,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 59.93,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 63.12,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 58.3,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 69.23,
				},
				[7] = {
					["gtype"] = 2,
					["x"] = 53.28,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 76.31999999999999,
				},
				[8] = {
					["gtype"] = 2,
					["x"] = 54.04,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 75.25,
				},
				[9] = {
					["gtype"] = 2,
					["x"] = 31.18,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 52.23,
				},
				[10] = {
					["gtype"] = 2,
					["x"] = 36.37,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 48.01,
				},
				[11] = {
					["gtype"] = 2,
					["x"] = 37.26,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 45.5,
				},
				[12] = {
					["gtype"] = 2,
					["x"] = 37.88,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 40.72,
				},
			},
			["gold vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 61.59,
					["count"] = 1,
					["icon"] = 5,
					["y"] = 41.09,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 69.95999999999999,
					["count"] = 1,
					["icon"] = 5,
					["y"] = 42.42,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 68.81,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 54.91,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 55.59,
					["count"] = 3,
					["icon"] = 5,
					["y"] = 72.84,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 48.29,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 79.7,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 27.24,
					["count"] = 3,
					["icon"] = 5,
					["y"] = 70.58,
				},
			},
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 71.13,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 42.35,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 35.88,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 50.46,
				},
			},
		},
		[29] = {
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 55.8,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 44.49,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 56.92,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 44.6,
				},
			},
		},
	},
	[2] = {
		[23] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 67.33,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 57.82,
				},
			},
		},
		[24] = {
			["silverleaf"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 40.83,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 25.25,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 41.9,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 31.14,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 55.4,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 39.97,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 50.83,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 20.11,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 39.58,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 16.46,
				},
			},
			["earthroot"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 41.5,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 17.22,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 45.97,
					["count"] = 2,
					["icon"] = 3,
					["y"] = 30.24,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 47.24,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 27.04,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 54.7,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 45.88,
				},
				[5] = {
					["gtype"] = 1,
					["x"] = 54.03,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 48.47,
				},
				[6] = {
					["gtype"] = 1,
					["x"] = 46.13,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 32.54,
				},
			},
			["peacebloom"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 38.17,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 26.33,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 38.76,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 28.06,
				},
				[3] = {
					["gtype"] = 1,
					["x"] = 47.1,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 25.52,
				},
				[4] = {
					["gtype"] = 1,
					["x"] = 47.35,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 20.14,
				},
			},
			["copper vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 44.52,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 16.05,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 50.13,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 46,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 50.4,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 44.23,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 45.41,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 15.44,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 48.07,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 22.18,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 44.99,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 26.42,
				},
				[7] = {
					["gtype"] = 2,
					["x"] = 44.35,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 26.49,
				},
				[8] = {
					["gtype"] = 2,
					["x"] = 45.08,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 48.56,
				},
				[9] = {
					["gtype"] = 2,
					["x"] = 44.9,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 49.78,
				},
				[10] = {
					["gtype"] = 2,
					["x"] = 46.15,
					["count"] = 3,
					["icon"] = 1,
					["y"] = 51.3,
				},
				[11] = {
					["gtype"] = 2,
					["x"] = 49.9,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 63.85,
				},
				[12] = {
					["gtype"] = 2,
					["x"] = 50.8,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 65.29000000000001,
				},
				[13] = {
					["gtype"] = 2,
					["x"] = 51.29,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 67.77,
				},
				[14] = {
					["gtype"] = 2,
					["x"] = 48.12,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 68.43000000000001,
				},
				[15] = {
					["gtype"] = 2,
					["x"] = 47.31,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 76.28,
				},
				[16] = {
					["gtype"] = 2,
					["x"] = 47.68,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 47.67,
				},
			},
		},
		[26] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 36.92,
					["count"] = 0,
					["icon"] = 7,
					["y"] = 54.15,
				},
			},
			["mithril deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 40.61,
					["count"] = 2,
					["icon"] = 6,
					["y"] = 51.84,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 43.39,
					["count"] = 3,
					["icon"] = 6,
					["y"] = 48.43,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 33.55,
					["count"] = 2,
					["icon"] = 6,
					["y"] = 41.79,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 29.86,
					["count"] = 2,
					["icon"] = 6,
					["y"] = 41.43,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 30.63,
					["count"] = 2,
					["icon"] = 6,
					["y"] = 39.52,
				},
			},
			["iron deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 43.12,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 49.35,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 41.44,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 43.81,
				},
			},
			["gold vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 44.21,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 47.92,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 42.14,
					["count"] = 3,
					["icon"] = 5,
					["y"] = 43.17,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 44.7,
					["count"] = 3,
					["icon"] = 5,
					["y"] = 26.44,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 48.05,
					["count"] = 2,
					["icon"] = 5,
					["y"] = 24.5,
				},
			},
		},
		[7] = {
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 63.75,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 27.64,
				},
			},
		},
		[30] = {
			["silverleaf"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 18.13,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 61.43,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 16.69,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 56.39,
				},
			},
			["tin vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 22.95,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 76.47,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 23.14,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 78.48,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 22.89,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 77.81,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 25.81,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 51.41,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 18.38,
					["count"] = 0,
					["icon"] = 2,
					["y"] = 77.25,
				},
			},
			["earthroot"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 11.21,
					["count"] = 1,
					["icon"] = 3,
					["y"] = 61.02,
				},
			},
			["copper vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 12.27,
					["count"] = 8,
					["icon"] = 1,
					["y"] = 60.23,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 12.54,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 72.20999999999999,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 13.41,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 69.06,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 13.34,
					["count"] = 9,
					["icon"] = 1,
					["y"] = 62.97,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 13.26,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 59.13,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 15.51,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 51.98,
				},
				[7] = {
					["gtype"] = 2,
					["x"] = 19.65,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 52.65,
				},
				[8] = {
					["gtype"] = 2,
					["x"] = 23.55,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 44.98,
				},
				[9] = {
					["gtype"] = 2,
					["x"] = 19.8,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 48.71,
				},
				[10] = {
					["gtype"] = 2,
					["x"] = 13.18,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 59.96,
				},
				[11] = {
					["gtype"] = 2,
					["x"] = 74.06,
					["count"] = 1,
					["icon"] = 1,
					["y"] = 56.46,
				},
			},
			["silver vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 27.09,
					["count"] = 0,
					["icon"] = 3,
					["y"] = 52.02,
				},
			},
			["mageroyal"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 12.54,
					["count"] = 3,
					["icon"] = 4,
					["y"] = 63.74,
				},
				[2] = {
					["gtype"] = 1,
					["x"] = 21.96,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 62.5,
				},
			},
			["peacebloom"] = {
				[1] = {
					["gtype"] = 1,
					["x"] = 20.64,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 57.54,
				},
			},
		},
		[16] = {
			["copper vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 32.57,
					["count"] = 2,
					["icon"] = 1,
					["y"] = 56.72,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 59.35,
					["count"] = 3,
					["icon"] = 1,
					["y"] = 70.47,
				},
			},
			["iron deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 70.44,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 66.11,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 70.03,
					["count"] = 1,
					["icon"] = 4,
					["y"] = 72.18000000000001,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 62.94,
					["count"] = 2,
					["icon"] = 4,
					["y"] = 74.86,
				},
			},
			["tin vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 54.59,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 19.74,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 54.92,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 23.57,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 53.85,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 27.86,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 66.64,
					["count"] = 2,
					["icon"] = 2,
					["y"] = 70.02,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 70.11,
					["count"] = 4,
					["icon"] = 2,
					["y"] = 43.76,
				},
			},
		},
		[33] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 59.18,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 64.58,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 59.13,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 65.12000000000001,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 54.04,
					["count"] = 2,
					["icon"] = 7,
					["y"] = 38.83,
				},
			},
			["mithril deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 55.22,
					["count"] = 4,
					["icon"] = 6,
					["y"] = 80.52,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 53.35,
					["count"] = 3,
					["icon"] = 6,
					["y"] = 71.29000000000001,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 40.06,
					["count"] = 3,
					["icon"] = 6,
					["y"] = 73.04000000000001,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 33.02,
					["count"] = 3,
					["icon"] = 6,
					["y"] = 67.16,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 33.14,
					["count"] = 3,
					["icon"] = 6,
					["y"] = 58.71,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 33.61,
					["count"] = 1,
					["icon"] = 6,
					["y"] = 53.57,
				},
				[7] = {
					["gtype"] = 2,
					["x"] = 89.90000000000001,
					["count"] = 1,
					["icon"] = 6,
					["y"] = 66.61,
				},
			},
			["large solid chest"] = {
				[1] = {
					["gtype"] = 0,
					["x"] = 44.02,
					["count"] = 1,
					["icon"] = 2,
					["y"] = 66.77,
				},
			},
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 65.22,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 60.52,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 44.57,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 42.49,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 43.72,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 36.87,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 47.42,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 27.75,
				},
				[5] = {
					["gtype"] = 2,
					["x"] = 60.71,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 49.42,
				},
				[6] = {
					["gtype"] = 2,
					["x"] = 65.02,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 38.55,
				},
				[7] = {
					["gtype"] = 2,
					["x"] = 66.90000000000001,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 54.21,
				},
				[8] = {
					["gtype"] = 2,
					["x"] = 48.73,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 23.82,
				},
				[9] = {
					["gtype"] = 2,
					["x"] = 47.73,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 38.31,
				},
			},
		},
		[5] = {
			["truesilver deposit"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 48.21,
					["count"] = 1,
					["icon"] = 7,
					["y"] = 13.76,
				},
			},
		},
			["small thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 47.34,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 71.26000000000001,
				},
				[2] = {
					["gtype"] = 2,
					["x"] = 66.20999999999999,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 84.65000000000001,
				},
				[3] = {
					["gtype"] = 2,
					["x"] = 52.84,
					["count"] = 0,
					["icon"] = 8,
					["y"] = 43.89,
				},
				[4] = {
					["gtype"] = 2,
					["x"] = 57.72,
					["count"] = 1,
					["icon"] = 8,
					["y"] = 49.34,
				},
			},
			["rich thorium vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 63.78,
					["count"] = 0,
					["icon"] = 9,
					["y"] = 29.91,
				},
			},
			["gold vein"] = {
				[1] = {
					["gtype"] = 2,
					["x"] = 77.81999999999999,
					["count"] = 1,
					["icon"] = 5,
					["y"] = 63.64,
				},
			},
		},
	}
	
Gatherer_SavedSettings_AccountWide = {
	["HideOnClick"] = 0,
	["minderTime"] = 5,
	["maxDist"] = 20,
	["interested"] = {
		[1] = {
			["briarthorn"] = true,
			["grave moss"] = true,
			["gromsblood"] = true,
			["silverleaf"] = true,
			["swiftthistle"] = true,
			["wintersbite"] = true,
			["black lotus"] = true,
			["earthroot"] = true,
			["sungrass"] = true,
			["firebloom"] = true,
			["goldthorn"] = true,
			["mageroyal"] = true,
			["icecap"] = true,
			["arthas' tears"] = true,
			["golden sansam"] = true,
			["wild steelbloom"] = true,
			["bruiseweed"] = true,
			["kingsblood"] = true,
			["blindweed"] = true,
			["fadeleaf"] = true,
			["dreamfoil"] = true,
			["mountain silversage"] = true,
			["plaguebloom"] = true,
			["purple lotus"] = true,
			["stranglekelp"] = true,
			["khadgar's whisker"] = true,
			["liferoot"] = true,
			["peacebloom"] = true,
			["ghost mushroom"] = true,
			["wildvine"] = true,
		},
		[2] = {
			["tin"] = true,
			["copper"] = true,
			["dark iron"] = true,
			["truesilver"] = true,
			["thorium (rich)"] = true,
			["mithril"] = true,
			["silver"] = true,
			["gold"] = true,
			["thorium"] = true,
			["iron"] = true,
		},
		[3] = {
		},
		[0] = {
			["bloodpetal"] = true,
			["whipper root"] = true,
			["box"] = true,
			["floating wreckage"] = true,
			["blood of heroes"] = true,
			["cask"] = true,
			["power crystal"] = true,
			["night dragon"] = true,
			["shellfish trap"] = true,
			["crate"] = true,
			["footlocker"] = true,
			["patch of elemental water"] = true,
			["barrel"] = true,
			["giant clam"] = true,
			["windblossom"] = true,
			["school"] = true,
			["un'goro soil"] = true,
			["chest"] = true,
			["songflower"] = true,
		},
	},
	["NoIconOnMinDist"] = 0,
	["filters"] = {
		[1] = "on",
		[2] = "on",
		[3] = "auto",
		[0] = "auto",
	},
	["HideOnButton"] = 0,
	["debug"] = true,
	["fadeDist"] = 60,
	["HideIcon"] = 0,
	["alphaUnderMinIcon"] = 80,
	["number"] = 10,
	["filterRecording"] = {
		[1] = false,
		[2] = false,
		[3] = false,
		[0] = false,
	},
	["guild"] = true,
	["locale"] = "enUS",
	["HideMiniNotes"] = 0,
	["iconSet"] = "shaded",
	["raid"] = false,
	["ShowOnClick"] = 0,
	["mapMinder"] = false,
	["IconSize"] = 12,
	["filter"] = "all",
	["Position"] = 12,
	["Radius"] = 80,
	["useMainmap"] = true,
	["rareOre"] = 0,
	["miniIconDist"] = 30,
	["useMinimapText"] = "on",
	["ToggleWorldNotes"] = 0,
	["logInfo"] = "on",
	["ShowOnMouse"] = 1,
	["showWorldMapFilters"] = 0,
	["Version"] = "1.1.2",
	["disableWMFreezeWorkaround"] = 1,
	["fadePerc"] = 80,
	["HideOnMouse"] = 1,
	["ShowOnButton"] = 0,
	["useMinimap"] = true,
}
